# Permalinks
permalink:           pretty

# Setup
title:               Gazedo
tagline:             welcome!
url:                 http://blog.gazedo.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Gazedo update
  url:               https://github.com/gazedo-update
  email:             webmaster+blog@gazedo.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/gazedo/blog-gazedo
#google_analytics:
#  id:                

# Gems
gems:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
